### ISSUE TITLE
A gift from China 10 years ago

### ISSUE THREAD

**Issue by pwnfox** [r4wd3r/Suborner#1]
https://www.d99net.net/News.asp?id=62
![image](https://user-images.githubusercontent.com/111500026/185368780-e7666a1a-ce67-4b1d-8085-2c65352c7a20.png)

**Comment by r4wd3r** [comment]
Thanks for sharing this! I did not know about this tool and will do more profound research about this to improve this attack detection (and find new ways to bypass d99 👍🏼
