### ISSUE TITLE
Error: You need SYSTEM privileges to suborn Windows :(

### ISSUE THREAD

**Issue by g33k247** [r4wd3r/Suborner#4]
Compiled Suborn.sln into x64 release and ran `.\Suborner.exe /username:suborner$ /password:Password.1` from an Administrator PS prompt

Received the following output:
`[x] Error: You need SYSTEM privileges to suborn Windows :(`

In your YouTube video and README,I don't see SYSTEM as a requirement. Not sure where to go with this from here. Please advise.

**Comment by r4wd3r** [comment]
Hey! Thanks for testing Suborner.

This was addressed in [Issue #2](https://github.com/r4wd3r/Suborner/issues/2). This is a persistence technique that requires SYSTEM privileges, since it dynamically crafts the account binaries and writes them to the SAM.
